version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build: .
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    tty: true # allocate a pseudo-TTY to be able to run npm command / to prevent container from exiting
    restart: unless-stopped # prevent the automatic start of containers when docker starts and when the containers were stopped manually
    volumes:
      - ./wordpress/wp-content/plugins/countdown:/src/
